version: "3.9"
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: employedb
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./forDocker:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  example:
    build: /
    environment:
      HOST_CONT_DB: postgresdb
    ports: 
      - "8888:8888"
    depends_on:
      - postgresdb    
