version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./InitDatabase:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
      
